### ISSUE TITLE
Your plan

### ISSUE THREAD

**Issue by saedyousef** [Aissaoui-Ahmed/Palestine#1]
What's your plan in this Repo? I'm interested

**Comment by Aissaoui-Ahmed** [comment]
@saedyousef Sorry for the slow response, you can suggest whatever you want

**Comment by saedyousef** [comment]
@Aissaoui-Ahmed No worries bro. I thought you were about to do some kind of github badges or whatever, I've already done such a thing when I saw this repo. Never the less, we still need more badges (with more styles) I guess.

[Here is the repo](https://github.com/saedyousef/StandWithPalestine)

**Comment by saedyousef** [comment]
You could close this issue as well, thanks ❤️
